DELETE FROM `script_texts` WHERE entry BETWEEN -1576022 AND -1576000;
INSERT IGNORE INTO `script_texts` (`entry`,`content_default`,`content_loc6`,`content_loc7`,`sound`,`type`,`language`,`comment`) VALUES
(-1576000,'You know what they say about curiosity.','¡Ya sabéis lo que dicen de la curiosidad!','¡Ya sabéis lo que dicen de la curiosidad!',13319,1,0,'telestra SAY_AGGRO'),
(-1576001,'Death becomes you!','¡La muerte te sienta bien!','¡La muerte te sienta bien!',13324,1,0,'telestra SAY_KILL'),
(-1576002,'Damn the... luck.','Maldita la suerte.','Maldita la suerte.',13320,1,0,'telestra SAY_DEATH'),
(-1576003,'Now to finish the job!','¡Ahora a terminar el trabajo!','¡Ahora a terminar el trabajo!',13323,1,0,'telestra SAY_MERGE'),
(-1576004,'I\'ll give you more than you can handle.','¡Tendréis más de lo que podéis soportar!','¡Tendréis más de lo que podéis soportar!',13321,1,0,'telestra SAY_SPLIT_1'),
(-1576005,'There\'s plenty of me to go around.','¡Tengo para dar y tomar!','¡Tengo para dar y tomar!',13322,1,0,'telestra SAY_SPLIT_2'),
(-1576006,'Noo!','¡Nooo!','¡Nooo!',13328,1,0,'ormorok SAY_AGGRO'),
(-1576007,'Aaggh!','¡Aaggh! ¡Matar!','¡Aaggh! ¡Matar!',13330,1,0,'ormorok SAY_DEATH'),
(-1576008,'Baaack!','¡Devolved!','¡Devolved!',13331,1,0,'ormorok SAY_REFLECT'),
(-1576009,'Bleeeed!','¡Corred!','¡Corred!',13332,1,0,'ormorok SAY_ICESPIKE'),
(-1576010,'???','Haik-tak hi-ta.','Haik-tak hi-ta.',13329,1,0,'ormorok SAY_KILL'),
(-1576011,'Chaos beckons.','El caos se avecina.','El caos se avecina.',13186,1,0,'anomalus SAY_AGGRO'),
(-1576012,'Of course.','Claro...','Claro...',13187,1,0,'anomalus SAY_DEATH'),
(-1576013,'Reality... unwoven.','La realidad... desterrada...','La realidad... desterrada...',13188,1,0,'anomalus SAY_RIFT'),
(-1576014,'Indestructible.','Indestructible...','Indestructible...',13189,1,0,'anomalus SAY_SHIELD'),
(-1576015,'Expiration... is necesarry.','La expiración... es necesaria...','La expiración... es necesaria...',13274,1,0,'anomalus SAY_KILL'),
(-1576016,'Preserve? Why? There\'s no truth in it. No no no... only in the taking! I see that now!','¿Conservar?, ¿para qué? No hay verdad en ello... No, no, no... ¡Sólo en lo que se quita!, ¡ahora lo veo claro!','¿Conservar?, ¿para qué? No hay verdad en ello... No, no, no... ¡Sólo en lo que se quita!, ¡ahora lo veo claro!',13450,1,0,'keristrasza SAY_AGGRO'),
(-1576017,'Stay. Enjoy your final moments.','Quedaos, ¡disfrutad de vuestros últimos momentos!','Quedaos, ¡disfrutad de vuestros últimos momentos!',13451,1,0,'keristrasza SAY_CRYSTAL_NOVA'),
(-1576018,'Finish it! Finish it! Kill me, or I swear by the Dragonqueen you\'ll never see daylight again!','¡Dadle fin! ¡DADLE FIN! ¡Matadme, o juro por la reina de los dragones que nunca volveréis a ver la luz del día!','¡Dadle fin! ¡DADLE FIN! ¡Matadme, o juro por la reina de los dragones que nunca volveréis a ver la luz del día!',13452,1,0,'keristrasza SAY_ENRAGE'),
(-1576019,'Now we\'ve come to the truth!','¡Ha llegado el momento de la verdad!','¡Ha llegado el momento de la verdad!',13453,1,0,'keristrasza SAY_KILL'),
(-1576020,'Dragonqueen... Life-Binder... preserve... me.','¡Reina de los dragones...! ¡Vinculadora de vida...! Consérvame.','¡Reina de los dragones...! ¡Vinculadora de vida...! Consérvame.',13454,1,0,'keristrasza SAY_DEATH'),
(-1576021,'%s opens a Chaotic Rift!','¡%s abre una Falla caótica!','¡%s abre una Falla caótica!',0,3,0,'EMOTE_GUARDIAN_PORTAL'),
(-1576022,'%s shields himself and divert his power to the rifts!','¡%s se protege y desvía su poder a las fallas!','¡%s se protege y desvía su poder a las fallas!',0,3,0,'EMOTE_DRAGONFLIGHT_PORTAL');

DELETE FROM `script_texts` WHERE entry BETWEEN -1601041 AND -1601025;
INSERT IGNORE INTO `script_texts` (`entry`,`content_default`,`content_loc6`,`content_loc7`,`sound`,`type`,`language`,`comment`) VALUES
(-1601025,'May the Light give me strength to provide a worthy challenge.','Que la luz me de fuerzas para ser un reto digno.','Que la luz me de fuerzas para ser un reto digno.',16246,1,0,'palestress SAY_AGGRO'),
(-1601026,'Take this time to consider your past deeds.','Aprovecha este tiempo para pensar en tus hazañas.','Aprovecha este tiempo para pensar en tus hazañas.',16248,1,0,'palestress SAY_SUMMON'),
(-1601027,'Even the darkest memory fades when confronted!','Incluso el recuerdo más oscuro se desvanece al afrontarlo.','Incluso el recuerdo más oscuro se desvanece al afrontarlo.',16249,1,0,'palestress SAY_SUMMON_DEFEAT'),
(-1601028,'Take your rest.','Descansa.','Descansa.',16250,1,0,'palestress SAY_SLAY1'),
(-1601029,'Be at ease.','Ve en paz.','Ve en paz.',16251,1,0,'palestress SAY_SLAY2'),
(-1601030,'Excellent work!','¡Un trabajo... excelente!','¡Un trabajo... excelente!',16252,1,0,'palestress SAY_DEATH'),
(-1601031,'Prepare yourselves!','¡¡PREPARAOS!!','¡¡PREPARAOS!!',16135,1,0,'eadric SAY_AGGRO'),
(-1601032,'Hammer of the Righteous!','¡Martillo del honrado!','¡Martillo del honrado!',16136,1,0,'eadric SAY_HAMMER'),
(-1601033,'You! You need more practice.','¡Oh! ¡Tú, tienes que practicar más!','¡Oh! ¡Tú, tienes que practicar más!',16137,1,0,'eadric SAY_SLAY1'),
(-1601034,'Nay, nay, and I say yet again nay! Not good enough.','¡No, no, y otra vez NO! ¡No, es, SUFICIENTE!','¡No, no, y otra vez NO! ¡No, es, SUFICIENTE!',16138,1,0,'eadric SAY_SLAY2'),
(-1601035,'I yield! I submit. Excellent work. May I run away now?','¡Me rindo! ¡Lo admito! ¡Un trabajo excelente! Mmm... ¿puedo escaparme ya?','¡Me rindo! ¡Lo admito! ¡Un trabajo excelente! Mmm... ¿puedo escaparme ya?',16139,1,0,'eadric SAY_DEATH'),
(-1601036,'This farce ends here!','¡Esta farsa acaba aquí!','¡Esta farsa acaba aquí!',16259,1,0,'blacknight SAY_AGGRO'),
(-1601037,'My rotting flesh was just getting in the way!','¡Me estorbaba esa carne putrefacta!','¡Me estorbaba esa carne putrefacta!',16262,1,0,'blacknight SAY_SKELETON'),
(-1601038,'I have no need for bones to best you!','¡No necesito huesos para vencerte!','¡No necesito huesos para vencerte!',16263,1,0,'blacknight SAY_GHOST'),
(-1601039,'Pathetic.','¡Patético!','¡Patético!',16260,1,0,'blacknight SAY_SLAY1'),
(-1601040,'A waste of flesh.','¡Otro desperdicio!','¡Otro desperdicio!',16261,1,0,'blacknight SAY_SLAY2'),
(-1601041,'No! I must not fail... again...','¡No! No debo fallar... otra vez...','¡No! No debo fallar... otra vez...',16264,1,0,'blacknight SAY_DEATH');
