DELETE FROM `script_texts` WHERE entry BETWEEN -1576022 AND -1576000;
INSERT IGNORE INTO `script_texts` (`entry`,`content_default`,`content_loc6`,`content_loc7`,`sound`,`type`,`language`,`comment`) VALUES
(-1576000,'You know what they say about curiosity.','¡Ya sabéis lo que dicen de la curiosidad!','¡Ya sabéis lo que dicen de la curiosidad!',13319,1,0,'telestra SAY_AGGRO'),
(-1576001,'Death becomes you!','¡La muerte te sienta bien!','¡La muerte te sienta bien!',13324,1,0,'telestra SAY_KILL'),
(-1576002,'Damn the... luck.','Maldita la suerte.','Maldita la suerte.',13320,1,0,'telestra SAY_DEATH'),
(-1576003,'Now to finish the job!','¡Ahora a terminar el trabajo!','¡Ahora a terminar el trabajo!',13323,1,0,'telestra SAY_MERGE'),
(-1576004,'I\'ll give you more than you can handle.','¡Tendréis más de lo que podéis soportar!','¡Tendréis más de lo que podéis soportar!',13321,1,0,'telestra SAY_SPLIT_1'),
(-1576005,'There\'s plenty of me to go around.','¡Tengo para dar y tomar!','¡Tengo para dar y tomar!',13322,1,0,'telestra SAY_SPLIT_2'),
(-1576006,'Noo!','¡Nooo!','¡Nooo!',13328,1,0,'ormorok SAY_AGGRO'),
(-1576007,'Aaggh!','¡Aaggh! ¡Matar!','¡Aaggh! ¡Matar!',13330,1,0,'ormorok SAY_DEATH'),
(-1576008,'Baaack!','¡Devolved!','¡Devolved!',13331,1,0,'ormorok SAY_REFLECT'),
(-1576009,'Bleeeed!','¡Corred!','¡Corred!',13332,1,0,'ormorok SAY_ICESPIKE'),
(-1576010,'???','Haik-tak hi-ta.','Haik-tak hi-ta.',13329,1,0,'ormorok SAY_KILL'),
(-1576011,'Chaos beckons.','El caos se avecina.','El caos se avecina.',13186,1,0,'anomalus SAY_AGGRO'),
(-1576012,'Of course.','Claro...','Claro...',13187,1,0,'anomalus SAY_DEATH'),
(-1576013,'Reality... unwoven.','La realidad... desterrada...','La realidad... desterrada...',13188,1,0,'anomalus SAY_RIFT'),
(-1576014,'Indestructible.','Indestructible...','Indestructible...',13189,1,0,'anomalus SAY_SHIELD'),
(-1576015,'Expiration... is necesarry.','La expiración... es necesaria...','La expiración... es necesaria...',13274,1,0,'anomalus SAY_KILL'),
(-1576016,'Preserve? Why? There\'s no truth in it. No no no... only in the taking! I see that now!','¿Conservar?, ¿para qué? No hay verdad en ello... No, no, no... ¡Sólo en lo que se quita!, ¡ahora lo veo claro!','¿Conservar?, ¿para qué? No hay verdad en ello... No, no, no... ¡Sólo en lo que se quita!, ¡ahora lo veo claro!',13450,1,0,'keristrasza SAY_AGGRO'),
(-1576017,'Stay. Enjoy your final moments.','Quedaos, ¡disfrutad de vuestros últimos momentos!','Quedaos, ¡disfrutad de vuestros últimos momentos!',13451,1,0,'keristrasza SAY_CRYSTAL_NOVA'),
(-1576018,'Finish it! Finish it! Kill me, or I swear by the Dragonqueen you\'ll never see daylight again!','¡Dadle fin! ¡DADLE FIN! ¡Matadme, o juro por la reina de los dragones que nunca volveréis a ver la luz del día!','¡Dadle fin! ¡DADLE FIN! ¡Matadme, o juro por la reina de los dragones que nunca volveréis a ver la luz del día!',13452,1,0,'keristrasza SAY_ENRAGE'),
(-1576019,'Now we\'ve come to the truth!','¡Ha llegado el momento de la verdad!','¡Ha llegado el momento de la verdad!',13453,1,0,'keristrasza SAY_KILL'),
(-1576020,'Dragonqueen... Life-Binder... preserve... me.','¡Reina de los dragones...! ¡Vinculadora de vida...! Consérvame.','¡Reina de los dragones...! ¡Vinculadora de vida...! Consérvame.',13454,1,0,'keristrasza SAY_DEATH'),
(-1576021,'%s opens a Chaotic Rift!','¡%s abre una Falla caótica!','¡%s abre una Falla caótica!',0,3,0,'EMOTE_GUARDIAN_PORTAL'),
(-1576022,'%s shields himself and divert his power to the rifts!','¡%s se protege y desvía su poder a las fallas!','¡%s se protege y desvía su poder a las fallas!',0,3,0,'EMOTE_DRAGONFLIGHT_PORTAL');
